# Generated by Django 5.1.7 on 2025-04-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_order_date_remove_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_confirmed',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='safaricom_till',
            field=models.CharField(default='8600480', help_text='Safaricom Till Number for payments', max_length=10),
        ),
    ]
